### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by louisefindlay23** [MLH-Fellowship/gitcord-bot#31]
A lot of features have been merged to staging so readme should be updated to reflect this.

- Update template areas
- Add Netlify deploy status badge
- Add a screenshot and link to PM2 Dashboard

**Comment by dtemir** [comment]
our bot!

**Comment by dtemir** [comment]
Demoing our bot!

**Comment by louisefindlay23** [comment]
Closed as of #87.
