### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by louisefindlay23** [MLH-Fellowship/gitcord-bot#32]
Create logo for GitCord (mix of Octocat and Discord brand? Black/white and lilac)

Add to Readme and Discord Bot

**Comment by dtemir** [comment]
checking the bot

**Comment by dtemir** [comment]
checking the bot

**Comment by dtemir** [comment]
checking the bot

**Comment by dtemir** [comment]
![gitcord-logo](https://user-images.githubusercontent.com/62047062/129291427-d0b8dcb9-0c58-479b-bdc1-153d63bf9a77.png)

**Comment by louisefindlay23** [comment]
Awesome, @dtemir. Looks great on Light mode. Does it look okay on Dark Mode? Will need to update readme header.
