### ISSUE TITLE
Setting up GitHub token doesn't reflect validity 

### ISSUE THREAD

**Issue by dtemir** [MLH-Fellowship/gitcord-bot#54]
When using `-github-info`, if I put a completely random string next to it, it will still say
 `"GitHub auth was successful. Use -github-issue-number with the number of the issue you'd like to comment on."`

![Screenshot from 2021-08-09 20-18-34](https://user-images.githubusercontent.com/62047062/128793793-dcd11291-23d5-44a4-a568-9156019672ea.png)

Ways to fix:
try `let octokit = new MyOctokit({ auth: githubToken });` with the token

**Comment by louisefindlay23** [comment]
@dtemir, would you like to work on this?

**Comment by dtemir** [comment]
@louisefindlay23 on it :)

**Comment by louisefindlay23** [comment]
Is this now working, @dtemir after merging #70 since you said the two were related?
