### ISSUE TITLE
Asks for GithubToken when `-lighthouse` is called

### ISSUE THREAD

**Issue by Inoxia25** [MLH-Fellowship/gitcord-bot#73]
When I just use the `-lighthouse` command, without using any of the github commands and entering the GithubToken, the bot asks to enter the token. Along with this, the lighthouse feature is not working, as mentioned in issue #69 

![image](https://user-images.githubusercontent.com/66139520/129183231-05f05a36-fd0d-4183-bd7d-41deaf1d445f.png)

**Comment by louisefindlay23** [comment]
Closed as of #74.
