### ISSUE TITLE
Bot Requests DB Before Users Put Tokens

### ISSUE THREAD

**Issue by dtemir** [MLH-Fellowship/gitcord-bot#80]
In `main.js`, we are calling `db.fetchGit` to fetch a GitHub token for users who run `-github-info`. This causes problems to new users who do not yet have a token, which would cause errors like this

    TypeError: Cannot read property 'token' of undefined
        at /home/damir/Git/pod-3.1.3-team-4/database.js:49:25
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at async fetchGitHubToken (/home/damir/Git/pod-3.1.3-team-4/database.js:44:12)
        at async Object.fetchGit (/home/damir/Git/pod-3.1.3-team-4/database.js:4:20)
    Message is: -github-info new_token
    Command is: github-info

I will put the `github-info` command in the exceptions in `main.js` among `lighthouse`, `tech-stack`, and `help` so that the bot wouldn't fetch tokens for those who are just trying to set it up.

**Comment by louisefindlay23** [comment]
Closed as of #81.
